# Generated by Django 6.0.2 on 2026-02-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_costo_anterior', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de costo antes de esta compra para ver variaciones', max_digits=10, null=True)),
                ('precio_compra_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'detalles_compra',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fh_compra', models.DateTimeField(auto_now_add=True)),
                ('numero_factura', models.CharField(help_text='Número de comprobante del proveedor', max_length=50)),
                ('total_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('PENDIENTE', 'Pendiente de Entrega'), ('ANULADA', 'Anulada')], default='RECIBIDA', max_length=15)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CREDITO', 'Crédito / Cuenta Corriente'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20)),
                ('fh_alta', models.DateTimeField(auto_now_add=True)),
                ('fh_baja', models.DateTimeField(blank=True, null=True)),
                ('fh_modificacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_caja', models.ForeignKey(blank=True, help_text='Caja de la cual sale el efectivo', null=True, on_delete=django.db.models.deletion.PROTECT, to='boxes.caja', verbose_name='Caja de Pago')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
            },
        ),
    ]
