# Generated by Django 6.0.2 on 2026-02-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_final_sistema', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_final_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('fh_apertura', models.DateTimeField(auto_now_add=True)),
                ('fh_cierre', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'cajas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_mov_caja', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=255)),
                ('origen', models.CharField(choices=[('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('MANUAL', 'Ajuste Manual'), ('GASTO', 'Gasto Operativo')], default='MANUAL', max_length=20)),
                ('fh_creacion', models.DateTimeField(auto_now_add=True)),
                ('fh_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimiento de la Caja',
                'verbose_name_plural': 'Movimientos de la caja',
                'db_table': 'movimientos_caja',
            },
        ),
    ]
