# Generated by Django 6.0.2 on 2026-02-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('cuit', models.CharField(max_length=20, unique=True, verbose_name='CUIT')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razon Social')),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preventista')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('fh_alta', models.DateTimeField(auto_now_add=True)),
                ('fh_modificacion', models.DateTimeField(auto_now=True)),
                ('fh_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
    ]
