# Generated by Django 6.0.2 on 2026-02-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo de compra en el momento de la venta', max_digits=10)),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total restado por promociones', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='products.producto')),
                ('id_promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.promocion')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'detalles_venta',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fh_venta', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_recibido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vuelto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=15)),
                ('fh_alta', models.DateTimeField(auto_now_add=True)),
                ('fh_modificacion', models.DateTimeField(auto_now=True)),
                ('fh_baja', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_caja', to='boxes.caja')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_cliente', to='customers.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
    ]
